version: '3.8'

services:
  app:
    build: .
    container_name: pg_card_mvp
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - pg_card_network
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: pg_card_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - pg_card_network
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: pg_card_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - pg_card_network
    env_file:
      - .env

volumes:
  db_data:

networks:
  pg_card_network:
    driver: bridge
